### ISSUE TITLE
In v2.0 capture file Lx bar 1 is mis-patched to the same address as Lx bar 3

### ISSUE THREAD

**Issue by skutov** [mikewoodld/TheatricalPrevisContest#10]
Title says it all really, in the v2.0 capture file Lx bar 1 trim responds on channel 6/203 and not 6/201 as expected.

**Comment by skutov** [comment]
Never mind, saw that this was fixed between me downloading the new file and posting this issue.

**Comment by mikewoodld** [comment]
:)
