### ISSUE TITLE
Channel 70 does not exist in patch

### ISSUE THREAD

**Issue by ghost** [mikewoodld/TheatricalPrevisContest#11]
Between lines 62 and 63 in the Patch Sheet v2.0, the channel numbers jump from 69 to 71.

This is a little speed bump for users who are copying the patch by hand, as channel 101 will run into a conflict when patching in sequence. (A.19 in use)

**Comment by mikewoodld** [comment]
That's because there are only 9 lights in the 60's system - it wouldn't make sense to start the next system at 70 when all the other ones start with X1 (Same reason there is no 80)

You're able to use any channel numbers you'd like, if my method doesn't work for you.
