### ISSUE TITLE
Capture (Mac) file displaying upside down

### ISSUE THREAD

**Issue by dLux587** [mikewoodld/TheatricalPrevisContest#13]
When I open the 2.0 Capture file for Mac, the orientation is default to front, but upside down. If I change it so that it's right side up, a few seconds later it switches back to being upside down. Not sure if this is a Capture issue or something with the file, but it wasn't occurring in v1.0.

Thanks! :)

**Comment by mikewoodld** [comment]
Do you have the camera controller patched?

**Comment by dLux587** [comment]
I'm working on that now - can you please clarify what address the camera should be patched to? Thanks Mike.

**Comment by mikewoodld** [comment]
https://github.com/mikewoodld/TheatricalPrevisContest/issues/5

**Comment by dLux587** [comment]
That solved the issue - thanks!

**Comment by mikewoodld** [comment]
Yay!
