### ISSUE TITLE
Midstage Black allows light to shine through it

### ISSUE THREAD

**Issue by mikewoodld** [mikewoodld/TheatricalPrevisContest#16]
User reports that the midstage black is allowing light to travel through it, as if by magic.

**Comment by mikewoodld** [comment]
Discovered that it was not a curtain from the Wizarding World and was, in fact, my fault. Will release v2.1 to address this issue.

**Comment by yamashitalighting** [comment]
The US Black does the same if that was unintentional. But, it has been incredibly useful if intentional.

**Comment by mikewoodld** [comment]
2.1 Has been created and uploaded. Please note, you do NOT need to update to this version unless you want the curtains to be fixed. If you are not using the ms/us curtains, there's no need to update.

https://github.com/mikewoodld/TheatricalPrevisContest/tree/master/v2.1

**Comment by mikewoodld** [comment]
> The US Black does the same if that was unintentional. But, it has been incredibly useful if intentional.

@bplights - it was unintentional, unfortunately. Are you using both the mid and the us in your design? If you're only using the US, you can stick with v2.0 and not worry about it.

**Comment by yamashitalighting** [comment]
> > The US Black does the same if that was unintentional. But, it has been incredibly useful if intentional.
> 
> @bplights - it was unintentional, unfortunately. Are you using both the mid and the us in your design? If you're only using the US, you can stick with v2.0 and not worry about it.

@mikewoodld I had intentions to work with the mid-stage, but I haven’t utilized it yet. I’ll play around with both files and see what works best. It _is_ theatre, where there’s a problem there’s either a work around or the idea gets cut. Thanks for the update though!
