### ISSUE TITLE
Scenery Request: Bed

### ISSUE THREAD

**Issue by LRTNZ** [mikewoodld/TheatricalPrevisContest#17]
Just started looking over this, and was thinking of a few different songs to try.
However I noticed: There is no bed! 
I noticed in the spreadsheets, that there were a few different things that were
included as they are "normal" Theatre things. 
I was wondering if a bed could be included, as I can think of many songs that would
be useful for, and also I think a bed can be said to be quite a normal Theatrical prop
to have to hand?

**Comment by mikewoodld** [comment]
Unfortunately at this point it’s too late in the game to add additional scenery
