### ISSUE TITLE
Fixtures not going to 0

### ISSUE THREAD

**Issue by JeremyBurdLighting** [mikewoodld/TheatricalPrevisContest#7]
I’m testing things and on my cue 3, a few fixtures are on @31. In cue 4, they’re suppose to bump to 0. I’ve loaded up cue 4, manually put them at 0, updated the cue and played it back, and they’re back @31. The fixtures specifically are channels 50, 54, 59, 63, and 67.

**Comment by mikewoodld** [comment]
This sounds like a programming problem to me as I'm not aware of any setting in Capture that would make this happen. Double check your programming to make sure you don't have something on a sub or secondary cue list.

If you're on a Mac and using sACN for your connection, you can download sACN Viewer to see what device is currently sending levels on your network to help you troubleshoot. But I'd bet money this is an EOS thing.
