### ISSUE TITLE
User Reported Issue: Screen Blanking

### ISSUE THREAD

**Issue by mikewoodld** [mikewoodld/TheatricalPrevisContest#8]
Mike,

 Here is the issue at the moment. I have patched the show, and everything looks good. Expect once patched, the curtain flys in, but I will take it out and the viz goes dark. As well I am able to turn on Ch 1-17 and get them to move and react but anything after will make the program go dark. 

I even went as far as to remove all automation but everything is still flown in, and I just feel like it was a patch issue but it feels like it is but I can't find it. Things are flashing and when I go through channel check it all feels right until some things don't trigger but there patch is correct.

I tried troubleshooting by re-doing the patch by your channel mode, check networking, etc. But hit a dead end. Anything you can suggest would be awesome!

I attached the patch file as a reference. LMK!

Thanks 

-D

**Comment by mikewoodld** [comment]
Can you be a little more specific by what you mean when you said it goes dark? I turned on channels 1 through 500 and it seems to work properly:

![PastedGraphic-3](https://user-images.githubusercontent.com/13637288/82528378-36cd0d00-9afe-11ea-86e4-d7850303742f.png)

Additionally, I put the upstage lights on, flew in the curtain, and flew it out. I did notice that when the curtain flew in, the light on the apron was still visible. Then when I flew it out, that light snapped out which Is definitely a graphics glitch, but everything else still worked. I found that this was not a consistent thing thought.


I have two ideas - I did experience some graphics issues depending on which computer and which version of the file I was running. I had one other person have a similar issue but restarting the capture file seemed to fix it - and it was a random issue, not specifically repeatable. 

1) try to recreate the problem and when it happens, don’t touch anything in EOS and instead, restart the Capture file. Does it restore to where it’s supposed to be, or does it still glitch?

2) Are you on a Mac? If so, head over to the GitHub and download the file that is labeled for “Intel GPUs” - let me know if you see any difference there, even if you don’t have the intel GPU.

**Comment by mikewoodld** [comment]
Verified that the user's patch was correct, though there were some issues with XYZ automations that ultimate wouldn't have an impact on the currently reported issue. 

Current possible solutions:
Graphics Problem - Switch to the other version
Other controllers on network?

**Comment by CaseyDoesLights** [comment]
I'm having the same issue and might be able to give a little more context on what's happening.

On my end, it seems to be related to the functions of the camera. When I try to control the ambiance by itself, I can take it completely out, leaving a fully dark screen, but I can't bring it back, and all other fixtures will stop responding half the time as well. At that point I have to restart the Capture file, sometimes multiple times, to get it going again. When I patched the camera itself, I had better control over ambiance and experienced the screen "blackout" less, but it would randomly switch me to top view every few seconds, and some systems of fixtures would pop in and out of visibility in live view.

I've gone through troubleshooting any network issues that might be causing this, and I'm coming up empty. I've also tried both versions of the Capture file with the same result. I wonder if it's a graphics issue on my end?

**Comment by mikewoodld** [comment]
@CaseyDoesLights Can you share your system specs? Model, OS, CPU, GPU?

Interested to see what might be causing this.

**Comment by CaseyDoesLights** [comment]
@mikewoodld Sure!

Model: Dell G5 15
OS: Microsoft 10
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
GPU: Intel UHD Graphics 630 (with the latest driver update)

**Comment by mikewoodld** [comment]
@CaseyDoesLights - I'm going to do an export of the presentation file backsaved to v2019 for windows for you to try. So far, everything you've been installed was made in Capture 2020. It might be tomorrow though

**Comment by mikewoodld** [comment]
@CaseyDoesLights I've added a backsaved version, let me know if this does anything to help. 

https://github.com/mikewoodld/TheatricalPrevisContest/tree/master/v2.0/2.0%20Experimental%20Windows%20Backsaved%20Version

**Comment by vpatech** [comment]
I have been having similar issues: Screen randomly flashing, random dark spots where the lights should be hitting and the computer running at full speed to keep up with the graphics card. I just loaded the 2019 version and so far its running smoother and less glitchy.

-Patrick B

**Comment by mikewoodld** [comment]
@vpatech - good to hear! I think the graphics problems here might be also related to the ones from https://github.com/mikewoodld/TheatricalPrevisContest/issues/14. I have reached out to Capture support to see if there's something I can do to make it better. 

Patrick, can you post your system specs just so we have the data point?

**Comment by vpatech** [comment]
Model: Dell Inspiron 13-5378
OS: Microsoft 10
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
GPU: Intel HD Graphics 620

**Comment by CaseyDoesLights** [comment]
This new file is working much better now! I'll let you know if any issues come up. Thanks!

**Comment by mikewoodld** [comment]
Original user was having issues because they had a secondary computer sending sACN data on their network and there were conflicts. Alternate files seem to be helping users who are having graphics issues.
